# Generated by Django 5.1.5 on 2025-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='memeber',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspace',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ContributorRole',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
