# Generated by Django 5.1.5 on 2025-01-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_membermodel_last_login'),
        ('workspace', '0002_remove_contributor_memeber_remove_contributor_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.AddField(
            model_name='workspace',
            name='contributors',
            field=models.ManyToManyField(to='membership.membermodel'),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('done', models.BooleanField(default=False)),
                ('contributors', models.ManyToManyField(to='membership.membermodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('suspend', 'Suspend'), ('done', 'Done')], default='todo', max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.board')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membermodel')),
            ],
        ),
    ]
