# Generated by Django 5.1.5 on 2025-01-29 10:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_remove_membermodel_role'),
        ('workspace', '0003_remove_workspace_owner_workspace_contributors_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributor',
        ),
        migrations.AddField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 10, 19, 28, 690813, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='board',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='contributors',
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('leader', 'Leader'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membermodel')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='contributors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.contributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='contributors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.contributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='contributors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.contributor'),
            preserve_default=False,
        ),
    ]
