# Generated by Django 5.1.5 on 2025-01-29 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_remove_membermodel_role'),
        ('workspace', '0004_remove_task_contributor_board_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contributors',
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['start'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='board',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='title',
        ),
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(related_name='boards', to='membership.membermodel'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='membership.membermodel'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='titlte', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own_Workspace', to='membership.membermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(related_name='Workspaces', to='membership.membermodel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspace.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('suspend', 'suspend'), ('done', 'done')], default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.AddField(
            model_name='board',
            name='Workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspace.workspace'),
        ),
    ]
