# Generated by Django 5.1.5 on 2025-02-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_remove_board_contributors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
    ]
