# Generated by Django 5.1.5 on 2025-02-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_remove_task_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='users',
            new_name='members',
        ),
    ]
