# Generated by Django 5.1.5 on 2025-02-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_rename_workspace_board_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='active',
            new_name='is_active',
        ),
    ]
