# Generated by Django 5.1.5 on 2025-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_rename_active_board_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, choices=[('new feature', 'New Feature'), ('refactoring', 'Refactoring'), ('bug fix', 'Bug Fix'), ('r&d', 'R&D')], max_length=20, null=True),
        ),
    ]
