# Generated by Django 5.1.5 on 2025-01-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUserModel',
            new_name='MemberModel',
        ),
    ]
