# Generated by Django 5.1.5 on 2025-01-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_rename_customeusermodel_membermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
