# Generated by Django 5.1.5 on 2025-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membermodel_email_alter_membermodel_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermodel',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
