# Generated by Django 5.1.5 on 2025-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_rename_isactive_membermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
