# Generated by Django 5.1.5 on 2025-01-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_membermodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('leader', 'Leader'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
