# Generated by Django 5.1.5 on 2025-01-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_membermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermodel',
            name='role',
        ),
    ]
