# Generated by Django 5.1.5 on 2025-02-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_remove_membermodel_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermodel',
            options={},
        ),
    ]
