# Generated by Django 5.1.4 on 2025-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeusermodel_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
