# Generated by Django 5.1.4 on 2025-01-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.commentmodel'),
        ),
    ]
