# Generated by Django 5.1.4 on 2025-01-08 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_commentmodel_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(null=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
