# Generated by Django 5.1.4 on 2025-01-10 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_post',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
