# Generated by Django 5.1.4 on 2025-01-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_picture_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='posts.picture'),
        ),
    ]
