# Generated by Django 5.1.4 on 2025-01-10 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_image_delete_picture_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_post',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
