# Generated by Django 5.1.4 on 2025-01-10 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_time_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_post',
            field=models.TimeField(default=datetime.datetime(2025, 1, 10, 21, 17, 29, 972313, tzinfo=datetime.timezone.utc)),
        ),
    ]
