# Generated by Django 5.1.4 on 2025-01-10 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_commentmodel_level_alter_post_time_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='style',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_post',
            field=models.TimeField(default=datetime.datetime(2025, 1, 10, 21, 39, 26, 432498, tzinfo=datetime.timezone.utc)),
        ),
    ]
